# Generated by Django 5.1.5 on 2025-01-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_cid',
            field=models.CharField(blank=True, help_text='IPFS Content Identifier for the image', max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename of the uploaded image', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage='posts.ipfs.IPFSStorage', upload_to='posts/'),
        ),
    ]
