# Generated by Django 5.1.5 on 2025-01-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_add_ipfs_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_cid',
            field=models.CharField(blank=True, help_text='IPFS Content Identifier for the profile picture', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_filename',
            field=models.CharField(blank=True, help_text='Original filename of the profile picture', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage='posts.ipfs.IPFSStorage', upload_to='profiles/'),
        ),
    ]
